- name: "install dependencies for phonenumber build"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - cmake
    - cmake-curses-gui
    - libprotobuf-dev
    - libgtest-dev
    - libre2-dev
    - libicu-dev
    - libboost-dev
    - libboost-thread-dev
    - libboost-system-dev
    - protobuf-compiler

- name: "install libphonenumber"
  shell: |
      set -e
      cd /tmp
      wget https://github.com/googlei18n/libphonenumber/archive/v{{ liphonenumber_version }}.tar.gz 2>/dev/null >&2
      tar xf v{{ liphonenumber_version }}.tar.gz
      cd libphonenumber-{{ liphonenumber_version }}
      mkdir build
      cd build
      cmake -DCMAKE_INSTALL_PREFIX=/usr ../cpp
      make -Wno-error=deprecated-declarations -j $(grep -c ^processor /proc/cpuinfo)
      cp *.a /usr/lib/
      cp *.so* /usr/lib
      cp -R ../cpp/src/phonenumbers /usr/include/
